spring:
  datasource:
    url: jdbc:TAOS://weiwei-ThinkStation-P920:6030/
    username: root
    password: taosdata
    driver-class-name: com.taosdata.jdbc.TSDBDriver

app:
  data-collection-interval: 10000 # 数据采集间隔，单位为毫秒
